export const MAX_TAG_COUNT = 20;
export const MAX_TAG_LENGTH = 40;

export const LANGUAGE_TAGS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "Dart",
  "Scala",
  "Haskell",
  "Elixir",
  "Shell",
  "PowerShell",
  "Objective-C",
  "Assembly",
  "Groovy",
  "Julia",
  "MATLAB",
  "R",
  "Perl",
  "Lua",
  "Zig",
  "Nim",
  "Crystal",
  "OCaml",
  "F#",
  "Scheme",
  "Common Lisp",
  "Ada",
  "Fortran",
  "COBOL",
  "Pascal",
  "Delphi",
  "Visual Basic",
  "VBScript",
  "Bash",
  "Zsh",
  "Tcl",
  "Prolog",
  "Erlang",
  "D",
  "Hack",
  "V",
  "Haxe",
  "GDScript",
  "Solidity",
  "Vala",
  "Red",
  "ReScript",
  "ReasonML",
  "PureScript",
  "Elm",
  "WebAssembly",
  "Squirrel",
  "Monkey C",
  "Pike",
  "Racket",
  "Smalltalk",
  "Self",
  "Io",
  "Awk",
  "Sed",
  "PostScript",
  "TeX",
  "Wolfram",
  "UnrealScript",
  "Pawn",
  "AngelScript",
  "AutoHotkey",
  "AutoIt",
  "Batchfile",
  "Makefile",
  "Nix",
  "HCL",
  "QML",
  "OpenCL",
  "GLSL",
  "HLSL",
  "Verilog",
  "VHDL",
  "SystemVerilog",
  "Chapel",
  "Idris",
  "Lean",
  "Coq",
  "Agda",
  "Mercury",
  "Nemerle",
  "Odin",
  "Carbon",
  "Mojo",
  "AppleScript",
  "CoffeeScript",
  "P4",
  "Ring",
  "Factor",
  "Fantom",
  "Fennel",
  "Hy",
  "J",
  "K",
  "Q#",
  "ABAP",
  "Apex",
  "PL/SQL",
  "T-SQL",
  "SQL",
  "GraphQL",
  "Scilab",
  "Octave",
  "Processing",
  "Arduino",
  "Vim script",
  "Emacs Lisp",
  "Lisp",
];

export const FRAMEWORK_TAGS = [
  "React",
  "Vue",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Express",
  "NestJS",
  "Fastify",
  "Django",
  "Flask",
  "FastAPI",
  "Spring",
  "Spring Boot",
  "Hibernate",
  "Laravel",
  "Symfony",
  "Ruby on Rails",
  "Flutter",
  "Ktor",
  "SwiftUI",
  "Vapor",
  "Gin",
  "Echo",
  "Actix",
  "Rocket",
  "Phoenix",
  "Play",
  "Akka",
  "Shiny",
  "Mojolicious",
  "LOVE",
  "Jester",
  "Kemal",
  "ASP.NET",
  "Qt",
  "Unreal Engine",
  "Unity",
  "Godot",
  "Hardhat",
  "Truffle",
  "GTK",
  "Electron",
  "Three.js",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "Chakra UI",
  "Redux",
  "MobX",
  "Zustand",
  "Socket.IO",
  "Apollo",
  "Celery",
  "Scrapy",
  "PyQt",
  "Kivy",
  "Fiber",
  "Micronaut",
  "Quarkus",
  "Dropwizard",
  "Struts",
  "Vaadin",
  "Inertia.js",
  "Alpine.js",
  "Lit",
  "Stencil",
  "Polymer",
  "Backbone.js",
  "Ember.js",
  "Meteor",
  "Sanic",
  "Tornado",
  "Bottle",
  "Pyramid",
  "CherryPy",
  "Hapi",
  "LoopBack",
  "AdonisJS",
  "FeathersJS",
  "Total.js",
  "Koa",
];

export const LIBRARY_TAGS = [
  "Lodash",
  "Axios",
  "Moment.js",
  "Day.js",
  "date-fns",
  "Ramda",
  "Underscore.js",
  "Chart.js",
  "D3.js",
  "GSAP",
  "Anime.js",
  "Swiper",
  "Leaflet",
  "Mapbox GL JS",
  "Zod",
  "Yup",
  "Joi",
  "Validator.js",
  "bcrypt",
  "jsonwebtoken",
  "Mongoose",
  "Sequelize",
  "Prisma",
  "TypeORM",
  "Knex.js",
  "Sharp",
  "Jimp",
  "Bull",
  "Agenda",
  "ioredis",
  "node-fetch",
  "superagent",
  "cors",
  "helmet",
  "NumPy",
  "Pandas",
  "Matplotlib",
  "Seaborn",
  "SciPy",
  "Scikit-learn",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "OpenCV",
  "BeautifulSoup",
  "Requests",
  "NLTK",
  "SpaCy",
  "FastText",
  "XGBoost",
  "LightGBM",
  "CatBoost",
  "SymPy",
  "Statsmodels",
  "Plotly",
  "Dash",
  "Streamlit",
  "Guava",
  "Apache Commons",
  "Jackson",
  "Gson",
  "Log4j",
  "SLF4J",
  "JUnit",
  "Mockito",
  "Lombok",
  "MapStruct",
  "Hibernate Validator",
  "Spring Data",
  "Spring Security",
  "Reactor",
  "Netty",
  "Eigen",
  "Boost",
  "SFML",
  "SDL",
  "QtCore",
  "QtWidgets",
  "Poco",
  "Tokio",
  "Serde",
  "Actix Web",
  "Reqwest",
  "Diesel",
  "Tera",
  "Yew",
  "Gin Gonic",
  "GORM",
  "Cobra",
  "Viper",
  "Buffalo",
  "Beego",
  "Ecto",
  "Plug",
  "ActiveRecord",
  "Sidekiq",
  "Puma",
  "RSpec",
  "Alamofire",
  "RxSwift",
  "SnapKit",
  "Retrofit",
  "OkHttp",
  "Glide",
  "Picasso",
  "Room",
  "Jetpack Compose",
  "RxJS",
  "NgRx",
  "Zustand Middleware",
  "React Query",
  "TanStack Query",
  "SWR",
  "Three Fiber",
  "Framer Motion",
  "SocketCluster",
  "PeerJS",
  "WebRTC",
  "SQLite",
  "PostgreSQL Driver",
  "MySQL Connector",
  "Redis Client",
  "Graphene",
  "Ariadne",
  "Celery Beat",
  "Flower",
  "Selenium",
  "Playwright",
  "Puppeteer",
  "Jest",
  "Mocha",
  "Chai",
  "Vitest",
  "Cypress",
  "Testing Library",
  "ESLint",
  "Prettier",
  "Babel",
  "Webpack",
  "Vite",
  "Rollup",
  "Parcel",
  "dotenv",
  "cross-env",
  "concurrently",
  "Firebase SDK",
  "Supabase",
  "Stripe SDK",
  "Auth0 SDK",
  "OpenAI SDK",
  "LangChain",
  "Hugging Face Transformers",
];

export const DOMAIN_TAGS = [
  "Frontend",
  "Backend",
  "Fullstack",
  "Node.js",
  "PostgreSQL",
  "AI",
  "LLM",
  "Data",
  "Security",
  "Unity",
  "Game",
  "Figma",
  "UI/UX",
  "Design System",
  "Motion",
  "Branding",
  "Portfolio",
  "GitHub",
  "보안",
  "데이터",
  "인공지능",
  "웹",
  "앱",
  "게임",
  "기획",
  "디자인",
];

export const TAG_OPTIONS = [
  ...DOMAIN_TAGS,
  ...LANGUAGE_TAGS,
  ...FRAMEWORK_TAGS,
  ...LIBRARY_TAGS,
];

export const normalizeTag = (value) =>
  String(value ?? "")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^#/, "")
    .slice(0, MAX_TAG_LENGTH);

export const parseTags = (value, { maxTags = MAX_TAG_COUNT } = {}) => {
  const source = Array.isArray(value) ? value : String(value ?? "").split(/[,，\n]/);
  const seen = new Set();
  const tags = [];

  source.forEach((entry) => {
    const tag = normalizeTag(entry);
    const key = tag.toLowerCase();
    if (!tag || seen.has(key) || tags.length >= maxTags) {
      return;
    }

    seen.add(key);
    tags.push(tag);
  });

  return tags;
};

export const formatTagsText = (tags = []) => parseTags(tags).join(", ");

export const suggestTags = ({
  input = "",
  selectedTags = [],
  options = TAG_OPTIONS,
  limit = 8,
} = {}) => {
  const query = normalizeTag(input).toLowerCase();
  const selected = new Set(parseTags(selectedTags).map((tag) => tag.toLowerCase()));

  return parseTags(options, { maxTags: options.length })
    .filter((tag) => !selected.has(tag.toLowerCase()))
    .filter((tag) => !query || tag.toLowerCase().includes(query))
    .slice(0, limit);
};
